import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ismail's App",
  description: "Generated by create next app",
};

const navStyles = {
  display: "flex",
  justifyContent: "space-evenly",
  padding: "30px",
  listStyleType: "none",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={navStyles}>
          <li>Blog</li>
          <li>Dashboard</li>
          <li>Ismail Dincer</li>
        </nav>
        {children}
      </body>
    </html>
  );
}
